// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: replication/proto/replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALEntry_EntryType int32

const (
	// ใช้สำหรับบันทึกข้อมูลอนุกรมเวลาใหม่
	WALEntry_PUT_EVENT WALEntry_EntryType = 0
	// ใช้สำหรับลบ series ทั้งหมดที่ตรงกับ metric และ tags
	WALEntry_DELETE_SERIES WALEntry_EntryType = 1
	// ใช้สำหรับลบข้อมูลในช่วงเวลาที่กำหนด
	WALEntry_DELETE_RANGE WALEntry_EntryType = 2
)

// Enum value maps for WALEntry_EntryType.
var (
	WALEntry_EntryType_name = map[int32]string{
		0: "PUT_EVENT",
		1: "DELETE_SERIES",
		2: "DELETE_RANGE",
	}
	WALEntry_EntryType_value = map[string]int32{
		"PUT_EVENT":     0,
		"DELETE_SERIES": 1,
		"DELETE_RANGE":  2,
	}
)

func (x WALEntry_EntryType) Enum() *WALEntry_EntryType {
	p := new(WALEntry_EntryType)
	*p = x
	return p
}

func (x WALEntry_EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALEntry_EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_proto_replication_proto_enumTypes[0].Descriptor()
}

func (WALEntry_EntryType) Type() protoreflect.EnumType {
	return &file_replication_proto_replication_proto_enumTypes[0]
}

func (x WALEntry_EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALEntry_EntryType.Descriptor instead.
func (WALEntry_EntryType) EnumDescriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{1, 0}
}

// StreamWALRequest คือ message ที่ follower ส่งไปหา leader ตอนเริ่มต้น stream
type StreamWALRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence number ของ entry ล่าสุดที่ follower ได้รับและประมวลผลสำเร็จ
	// leader จะเริ่มส่งข้อมูลตั้งแต่ entry ที่อยู่ถัดจากหมายเลขนี้
	FromSequenceNumber uint64 `protobuf:"varint,1,opt,name=from_sequence_number,json=fromSequenceNumber,proto3" json:"from_sequence_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamWALRequest) Reset() {
	*x = StreamWALRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWALRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWALRequest) ProtoMessage() {}

func (x *StreamWALRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWALRequest.ProtoReflect.Descriptor instead.
func (*StreamWALRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *StreamWALRequest) GetFromSequenceNumber() uint64 {
	if x != nil {
		return x.FromSequenceNumber
	}
	return 0
}

// WALEntry คือข้อมูลการเปลี่ยนแปลงหนึ่งรายการที่ถูกส่งผ่าน stream
type WALEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	EntryType      WALEntry_EntryType     `protobuf:"varint,2,opt,name=entry_type,json=entryType,proto3,enum=replication.WALEntry_EntryType" json:"entry_type,omitempty"`
	Metric         string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // สำหรับ PUT_EVENT
	Fields         *structpb.Struct       `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`                         // สำหรับ PUT_EVENT
	StartTime      int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // สำหรับ DELETE_RANGE
	EndTime        int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // สำหรับ DELETE_RANGE
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WALEntry) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WALEntry) GetEntryType() WALEntry_EntryType {
	if x != nil {
		return x.EntryType
	}
	return WALEntry_PUT_EVENT
}

func (x *WALEntry) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *WALEntry) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WALEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WALEntry) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *WALEntry) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *WALEntry) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_replication_proto_replication_proto protoreflect.FileDescriptor

const file_replication_proto_replication_proto_rawDesc = "" +
	"\n" +
	"#replication/proto/replication.proto\x12\vreplication\x1a\x1cgoogle/protobuf/struct.proto\"D\n" +
	"\x10StreamWALRequest\x120\n" +
	"\x14from_sequence_number\x18\x01 \x01(\x04R\x12fromSequenceNumber\"\xc3\x03\n" +
	"\bWALEntry\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12>\n" +
	"\n" +
	"entry_type\x18\x02 \x01(\x0e2\x1f.replication.WALEntry.EntryTypeR\tentryType\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x123\n" +
	"\x04tags\x18\x04 \x03(\v2\x1f.replication.WALEntry.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12/\n" +
	"\x06fields\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06fields\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\tEntryType\x12\r\n" +
	"\tPUT_EVENT\x10\x00\x12\x11\n" +
	"\rDELETE_SERIES\x10\x01\x12\x10\n" +
	"\fDELETE_RANGE\x10\x022[\n" +
	"\x12ReplicationService\x12E\n" +
	"\tStreamWAL\x12\x1d.replication.StreamWALRequest\x1a\x15.replication.WALEntry\"\x000\x01B3Z1github.com/iDanielLaw/nexusbase/replication/protob\x06proto3"

var (
	file_replication_proto_replication_proto_rawDescOnce sync.Once
	file_replication_proto_replication_proto_rawDescData []byte
)

func file_replication_proto_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)))
	})
	return file_replication_proto_replication_proto_rawDescData
}

var file_replication_proto_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_replication_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_replication_proto_replication_proto_goTypes = []any{
	(WALEntry_EntryType)(0),  // 0: replication.WALEntry.EntryType
	(*StreamWALRequest)(nil), // 1: replication.StreamWALRequest
	(*WALEntry)(nil),         // 2: replication.WALEntry
	nil,                      // 3: replication.WALEntry.TagsEntry
	(*structpb.Struct)(nil),  // 4: google.protobuf.Struct
}
var file_replication_proto_replication_proto_depIdxs = []int32{
	0, // 0: replication.WALEntry.entry_type:type_name -> replication.WALEntry.EntryType
	3, // 1: replication.WALEntry.tags:type_name -> replication.WALEntry.TagsEntry
	4, // 2: replication.WALEntry.fields:type_name -> google.protobuf.Struct
	1, // 3: replication.ReplicationService.StreamWAL:input_type -> replication.StreamWALRequest
	2, // 4: replication.ReplicationService.StreamWAL:output_type -> replication.WALEntry
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_replication_proto_replication_proto_init() }
func file_replication_proto_replication_proto_init() {
	if File_replication_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_replication_proto_depIdxs,
		EnumInfos:         file_replication_proto_replication_proto_enumTypes,
		MessageInfos:      file_replication_proto_replication_proto_msgTypes,
	}.Build()
	File_replication_proto_replication_proto = out.File
	file_replication_proto_replication_proto_goTypes = nil
	file_replication_proto_replication_proto_depIdxs = nil
}
