// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: replication/proto/replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALEntry_EntryType int32

const (
	// ใช้สำหรับบันทึกข้อมูลอนุกรมเวลาใหม่
	WALEntry_PUT_EVENT WALEntry_EntryType = 0
	// ใช้สำหรับลบ series ทั้งหมดที่ตรงกับ metric และ tags
	WALEntry_DELETE_SERIES WALEntry_EntryType = 1
	// ใช้สำหรับลบข้อมูลในช่วงเวลาที่กำหนด
	WALEntry_DELETE_RANGE WALEntry_EntryType = 2
)

// Enum value maps for WALEntry_EntryType.
var (
	WALEntry_EntryType_name = map[int32]string{
		0: "PUT_EVENT",
		1: "DELETE_SERIES",
		2: "DELETE_RANGE",
	}
	WALEntry_EntryType_value = map[string]int32{
		"PUT_EVENT":     0,
		"DELETE_SERIES": 1,
		"DELETE_RANGE":  2,
	}
)

func (x WALEntry_EntryType) Enum() *WALEntry_EntryType {
	p := new(WALEntry_EntryType)
	*p = x
	return p
}

func (x WALEntry_EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALEntry_EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_proto_replication_proto_enumTypes[0].Descriptor()
}

func (WALEntry_EntryType) Type() protoreflect.EnumType {
	return &file_replication_proto_replication_proto_enumTypes[0]
}

func (x WALEntry_EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALEntry_EntryType.Descriptor instead.
func (WALEntry_EntryType) EnumDescriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{1, 0}
}

// สถานะสุขภาพของ node
type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN   HealthCheckResponse_Status = 0
	HealthCheckResponse_HEALTHY   HealthCheckResponse_Status = 1
	HealthCheckResponse_UNHEALTHY HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_proto_replication_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_replication_proto_replication_proto_enumTypes[1]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{8, 0}
}

// StreamWALRequest คือ message ที่ follower ส่งไปหา leader ตอนเริ่มต้น stream
type StreamWALRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence number ของ entry ล่าสุดที่ follower ได้รับและประมวลผลสำเร็จ
	// leader จะเริ่มส่งข้อมูลตั้งแต่ entry ที่อยู่ถัดจากหมายเลขนี้
	FromSequenceNumber uint64 `protobuf:"varint,1,opt,name=from_sequence_number,json=fromSequenceNumber,proto3" json:"from_sequence_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamWALRequest) Reset() {
	*x = StreamWALRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWALRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWALRequest) ProtoMessage() {}

func (x *StreamWALRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWALRequest.ProtoReflect.Descriptor instead.
func (*StreamWALRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *StreamWALRequest) GetFromSequenceNumber() uint64 {
	if x != nil {
		return x.FromSequenceNumber
	}
	return 0
}

// WALEntry คือข้อมูลการเปลี่ยนแปลงหนึ่งรายการที่ถูกส่งผ่าน stream
type WALEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	EntryType      WALEntry_EntryType     `protobuf:"varint,2,opt,name=entry_type,json=entryType,proto3,enum=replication.WALEntry_EntryType" json:"entry_type,omitempty"`
	Metric         string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // สำหรับ PUT_EVENT
	Fields         *structpb.Struct       `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`                         // สำหรับ PUT_EVENT
	StartTime      int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // สำหรับ DELETE_RANGE
	EndTime        int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // สำหรับ DELETE_RANGE
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WALEntry) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WALEntry) GetEntryType() WALEntry_EntryType {
	if x != nil {
		return x.EntryType
	}
	return WALEntry_PUT_EVENT
}

func (x *WALEntry) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *WALEntry) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WALEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WALEntry) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *WALEntry) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *WALEntry) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetLatestSnapshotInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotInfoRequest) Reset() {
	*x = GetLatestSnapshotInfoRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotInfoRequest) ProtoMessage() {}

func (x *GetLatestSnapshotInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotInfoRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{2}
}

type SnapshotInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastWalSequenceNumber uint64                 `protobuf:"varint,2,opt,name=last_wal_sequence_number,json=lastWalSequenceNumber,proto3" json:"last_wal_sequence_number,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SizeBytes             int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_replication_proto_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotInfo) GetLastWalSequenceNumber() uint64 {
	if x != nil {
		return x.LastWalSequenceNumber
	}
	return 0
}

func (x *SnapshotInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SnapshotInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type StreamSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID ของ snapshot ที่ต้องการจะ stream ซึ่งได้มาจาก GetLatestSnapshotInfo
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSnapshotRequest) Reset() {
	*x = StreamSnapshotRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSnapshotRequest) ProtoMessage() {}

func (x *StreamSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSnapshotRequest.ProtoReflect.Descriptor instead.
func (*StreamSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{4}
}

func (x *StreamSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SnapshotChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*SnapshotChunk_FileInfo
	//	*SnapshotChunk_ChunkData
	Content       isSnapshotChunk_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_replication_proto_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotChunk) GetContent() isSnapshotChunk_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SnapshotChunk) GetFileInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Content.(*SnapshotChunk_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *SnapshotChunk) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Content.(*SnapshotChunk_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isSnapshotChunk_Content interface {
	isSnapshotChunk_Content()
}

type SnapshotChunk_FileInfo struct {
	// message แรกใน stream จะเป็น metadata ของไฟล์
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type SnapshotChunk_ChunkData struct {
	// message ต่อๆ ไปจะเป็นส่วนของเนื้อหาไฟล์
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*SnapshotChunk_FileInfo) isSnapshotChunk_Content() {}

func (*SnapshotChunk_ChunkData) isSnapshotChunk_Content() {}

type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path ของไฟล์ที่สัมพันธ์กับไดเรกทอรีของ snapshot
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// SHA256 checksum ของเนื้อหาไฟล์ทั้งหมดในรูปแบบ hex string
	Checksum      string `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_replication_proto_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state  protoimpl.MessageState     `protogen:"open.v1"`
	Status HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=replication.HealthCheckResponse_Status" json:"status,omitempty"`
	// Sequence number ล่าสุดที่ node ได้ประมวลผล
	LastAppliedSequence uint64 `protobuf:"varint,2,opt,name=last_applied_sequence,json=lastAppliedSequence,proto3" json:"last_applied_sequence,omitempty"`
	// Timestamp ของเวลาที่ node ประมวลผล entry ล่าสุด (optional)
	LastAppliedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_applied_at,json=lastAppliedAt,proto3" json:"last_applied_at,omitempty"`
	// ข้อมูลเพิ่มเติมเกี่ยวกับสถานะ
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_replication_proto_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetLastAppliedSequence() uint64 {
	if x != nil {
		return x.LastAppliedSequence
	}
	return 0
}

func (x *HealthCheckResponse) GetLastAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAppliedAt
	}
	return nil
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_replication_proto_replication_proto protoreflect.FileDescriptor

const file_replication_proto_replication_proto_rawDesc = "" +
	"\n" +
	"#replication/proto/replication.proto\x12\vreplication\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x10StreamWALRequest\x120\n" +
	"\x14from_sequence_number\x18\x01 \x01(\x04R\x12fromSequenceNumber\"\xc3\x03\n" +
	"\bWALEntry\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12>\n" +
	"\n" +
	"entry_type\x18\x02 \x01(\x0e2\x1f.replication.WALEntry.EntryTypeR\tentryType\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x123\n" +
	"\x04tags\x18\x04 \x03(\v2\x1f.replication.WALEntry.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12/\n" +
	"\x06fields\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06fields\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\tEntryType\x12\r\n" +
	"\tPUT_EVENT\x10\x00\x12\x11\n" +
	"\rDELETE_SERIES\x10\x01\x12\x10\n" +
	"\fDELETE_RANGE\x10\x02\"\x1e\n" +
	"\x1cGetLatestSnapshotInfoRequest\"\xb1\x01\n" +
	"\fSnapshotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x18last_wal_sequence_number\x18\x02 \x01(\x04R\x15lastWalSequenceNumber\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"'\n" +
	"\x15StreamSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\rSnapshotChunk\x124\n" +
	"\tfile_info\x18\x01 \x01(\v2\x15.replication.FileInfoH\x00R\bfileInfo\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\acontent\":\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"\x14\n" +
	"\x12HealthCheckRequest\"\x9b\x02\n" +
	"\x13HealthCheckResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.replication.HealthCheckResponse.StatusR\x06status\x122\n" +
	"\x15last_applied_sequence\x18\x02 \x01(\x04R\x13lastAppliedSequence\x12B\n" +
	"\x0flast_applied_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastAppliedAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"1\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x022\xe6\x02\n" +
	"\x12ReplicationService\x12E\n" +
	"\tStreamWAL\x12\x1d.replication.StreamWALRequest\x1a\x15.replication.WALEntry\"\x000\x01\x12_\n" +
	"\x15GetLatestSnapshotInfo\x12).replication.GetLatestSnapshotInfoRequest\x1a\x19.replication.SnapshotInfo\"\x00\x12T\n" +
	"\x0eStreamSnapshot\x12\".replication.StreamSnapshotRequest\x1a\x1a.replication.SnapshotChunk\"\x000\x01\x12R\n" +
	"\vHealthCheck\x12\x1f.replication.HealthCheckRequest\x1a .replication.HealthCheckResponse\"\x00B0Z.github.com/INLOpen/nexusbase/replication/protob\x06proto3"

var (
	file_replication_proto_replication_proto_rawDescOnce sync.Once
	file_replication_proto_replication_proto_rawDescData []byte
)

func file_replication_proto_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)))
	})
	return file_replication_proto_replication_proto_rawDescData
}

var file_replication_proto_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_replication_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_replication_proto_replication_proto_goTypes = []any{
	(WALEntry_EntryType)(0),              // 0: replication.WALEntry.EntryType
	(HealthCheckResponse_Status)(0),      // 1: replication.HealthCheckResponse.Status
	(*StreamWALRequest)(nil),             // 2: replication.StreamWALRequest
	(*WALEntry)(nil),                     // 3: replication.WALEntry
	(*GetLatestSnapshotInfoRequest)(nil), // 4: replication.GetLatestSnapshotInfoRequest
	(*SnapshotInfo)(nil),                 // 5: replication.SnapshotInfo
	(*StreamSnapshotRequest)(nil),        // 6: replication.StreamSnapshotRequest
	(*SnapshotChunk)(nil),                // 7: replication.SnapshotChunk
	(*FileInfo)(nil),                     // 8: replication.FileInfo
	(*HealthCheckRequest)(nil),           // 9: replication.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 10: replication.HealthCheckResponse
	nil,                                  // 11: replication.WALEntry.TagsEntry
	(*structpb.Struct)(nil),              // 12: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_replication_proto_replication_proto_depIdxs = []int32{
	0,  // 0: replication.WALEntry.entry_type:type_name -> replication.WALEntry.EntryType
	11, // 1: replication.WALEntry.tags:type_name -> replication.WALEntry.TagsEntry
	12, // 2: replication.WALEntry.fields:type_name -> google.protobuf.Struct
	13, // 3: replication.SnapshotInfo.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: replication.SnapshotChunk.file_info:type_name -> replication.FileInfo
	1,  // 5: replication.HealthCheckResponse.status:type_name -> replication.HealthCheckResponse.Status
	13, // 6: replication.HealthCheckResponse.last_applied_at:type_name -> google.protobuf.Timestamp
	2,  // 7: replication.ReplicationService.StreamWAL:input_type -> replication.StreamWALRequest
	4,  // 8: replication.ReplicationService.GetLatestSnapshotInfo:input_type -> replication.GetLatestSnapshotInfoRequest
	6,  // 9: replication.ReplicationService.StreamSnapshot:input_type -> replication.StreamSnapshotRequest
	9,  // 10: replication.ReplicationService.HealthCheck:input_type -> replication.HealthCheckRequest
	3,  // 11: replication.ReplicationService.StreamWAL:output_type -> replication.WALEntry
	5,  // 12: replication.ReplicationService.GetLatestSnapshotInfo:output_type -> replication.SnapshotInfo
	7,  // 13: replication.ReplicationService.StreamSnapshot:output_type -> replication.SnapshotChunk
	10, // 14: replication.ReplicationService.HealthCheck:output_type -> replication.HealthCheckResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_replication_proto_replication_proto_init() }
func file_replication_proto_replication_proto_init() {
	if File_replication_proto_replication_proto != nil {
		return
	}
	file_replication_proto_replication_proto_msgTypes[5].OneofWrappers = []any{
		(*SnapshotChunk_FileInfo)(nil),
		(*SnapshotChunk_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_replication_proto_depIdxs,
		EnumInfos:         file_replication_proto_replication_proto_enumTypes,
		MessageInfos:      file_replication_proto_replication_proto_msgTypes,
	}.Build()
	File_replication_proto_replication_proto = out.File
	file_replication_proto_replication_proto_goTypes = nil
	file_replication_proto_replication_proto_depIdxs = nil
}
